/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./HW01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l HW01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 * To build:
 * ./gradlew build
 */
public class App {
    public static void main(String... args) {
       //реализация класса HelloOtus
        String a1, a2;
        a1 = "aaa";
        a2 = "aaa";
        HelloOtus helloOtus = new HelloOtus();
        if (helloOtus.objectEqual(a1, a2)) System.out.println("\"" + a1 + "\"" + " identical " + "\"" + a2 + "\"");
        //было в примере, не стал убирать
        List<Integer> example = new ArrayList<>();
        int min = 0;
        int max = 100;
        for (int i = min; i < max; i++) {
            example.add(i);
        }
        System.out.println(Lists.reverse(example));
    }
}
